AWSTemplateFormatVersion: 2010-09-09

Parameters:
  tagEnvironment:
    Type: String
    Default: "non-production"
  tagOwner:
    Type: String
    Default: "fog"
  tagService:
    Type: String
    Default: "aws-metric-streams-client"
  tagSystem:
    Type: String
    Default: "fog"
  tagProduct:
    Type: String
    Default: "GOV.UK One Login"

Resources:
  CodeStarConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: GDS-GitHub-Connection-Gitsync
      ProviderType: GitHub
      Tags:
        - Key: Environment
          Value: !Ref tagEnvironment
        - Key: Owner
          Value: !Ref tagOwner
        - Key: Service
          Value: !Ref tagService
        - Key: System
          Value: !Ref tagSystem
        - Key: Product
          Value: !Ref tagProduct

Outputs:
  ConnectionArn:
    Description: "The ARN of the codestar connection"
    Value: !GetAtt CodeStarConnection.ConnectionArn
    Export:
      Name: "ConnectionArn"