version: 0.2
phases:
  build:
    commands:
      - cd infrastructure/gitsync-core/step-1 
      - ./deploy.sh Gitsync-core production GDS-GitHub-Connection main observability-infrastructure DynatraceSecrets