name: Pull Request to Main
# On a pull request make sure terraform is formatted and valid.

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - main
  workflow_dispatch:

jobs:
  check_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Terraform
        run: |
          cd terraform
          terraform init -backend=false
          terraform fmt -recursive -diff -check
          
          for module in ./aws
          do
            cd ${module}
            terraform init -backend=false
            terraform validate
            cd -
          done
          
          for module in ./modules
          do
            cd ${module}
            terraform init -backend=false
            terraform validate
            cd -
          done
          
          terraform validate
